packages:
  - 'packages/*'
  - 'examples/*'

overrides:
  typescript: $typescript

packageExtensions:
  '@vitest/browser':
    peerDependencies:
      '@vitest/runner': '*'

allowBuilds:
  esbuild: true
