/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/posts': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get all blog posts */
        get: operations['getPosts']
        put?: never
        /** Create a new blog post */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreatePostRequest']
                }
            }
            responses: {
                /** @description Post created */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Post']
                    }
                }
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/posts/{postId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get a single post by ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    postId: string
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description The requested post */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Post']
                    }
                }
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        /** Update a blog post */
        put: {
            parameters: {
                query?: never
                header?: never
                path: {
                    postId: string
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['UpdatePostRequest']
                }
            }
            responses: {
                /** @description Post updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Post']
                    }
                }
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/posts/{postId}/comments': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get comments for a post */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    postId: string
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description List of comments */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Comment'][]
                    }
                }
            }
        }
        put?: never
        /** Add a comment to a post */
        post: {
            parameters: {
                query?: never
                header?: never
                path: {
                    postId: string
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateCommentRequest']
                }
            }
            responses: {
                /** @description Comment created */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Comment']
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        Post: {
            id: string
            title: string
            content: string
            author: string
            /** Format: date-time */
            createdAt: string
            /** Format: date-time */
            updatedAt?: string
        }
        CreatePostRequest: {
            title: string
            content: string
            author: string
        }
        UpdatePostRequest: {
            title?: string
            content?: string
        }
        Comment: {
            id: string
            postId: string
            text: string
            author: string
            /** Format: date-time */
            createdAt: string
        }
        CreateCommentRequest: {
            text: string
            author: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    getPosts: {
        parameters: {
            query?: {
                limit?: number
                offset?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description List of posts */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Post'][]
                }
            }
        }
    }
}
